const FifthCardData = [
  {
    id: "sl5-prod-501",
    title: "Logitech MX Master 3S Wireless Mouse",
    image: "https://m.media-amazon.com/images/I/71nVIiWEcgL._AC_SY200_.jpg",
    price: 99.00,
    oldPrice: 125.00,
    rating: 4.8,
    reviewsCount: "25,400",
    description: "Quiet clicks and 8K DPI tracking for any surface. The ultimate ergonomic mouse for creators.",
  },
  {
    id: "sl5-prod-502",
    title: "ASUS Zenbook Duo Dual Screen Laptop",
    image: "https://m.media-amazon.com/images/I/719R46dVUTL._AC_SY200_.jpg",
    price: 1499.00,
    oldPrice: 1699.00,
    rating: 4.7,
    reviewsCount: "3,200",
    description: "Revolutionary dual-screen design with 4K OLED display for maximum productivity and multitasking.",
  },
  {
    id: "sl5-prod-503",
    title: "Netgear Nighthawk Tri-Band Wi-Fi 6 Router",
    image: "https://m.media-amazon.com/images/I/61aPY8odPSL._AC_SY200_.jpg",
    price: 299.50,
    oldPrice: 350.00,
    rating: 4.6,
    reviewsCount: "12,150",
    description: "Blazing fast internet speeds for gaming and streaming across 40+ devices simultaneously.",
  },
  {
    id: "sl5-prod-504",
    title: "Apple Magic Keyboard with Touch ID",
    image: "https://m.media-amazon.com/images/I/414C25OyjML._AC_SY200_.jpg",
    price: 149.00,
    oldPrice: 179.00,
    rating: 4.9,
    reviewsCount: "45,000",
    description: "Incredibly comfortable and precise typing experience with seamless wireless connectivity.",
  },
  {
    id: "sl5-prod-505",
    title: "WD Black 2TB SN850X NVMe Internal SSD",
    image: "https://m.media-amazon.com/images/I/51+oMO+PTeL._AC_SY200_.jpg",
    price: 165.99,
    oldPrice: 199.00,
    rating: 4.8,
    reviewsCount: "8,900",
    description: "Top-tier performance storage for gamers and pro-users with speeds up to 7300MB/s.",
  },
  {
    id: "sl5-prod-506",
    title: "Corsair Vengeance RGB 32GB DDR5 RAM Kit",
    image: "https://m.media-amazon.com/images/I/51IFiSD+kCL._AC_SY200_.jpg",
    price: 125.00,
    oldPrice: 150.00,
    rating: 4.7,
    reviewsCount: "5,400",
    description: "Optimized performance for Intel and AMD motherboards with stunning dynamic RGB lighting.",
  },
  {
    id: "sl5-prod-507",
    title: "Samsung Odyssey G9 49-inch Curved Monitor",
    image: "https://m.media-amazon.com/images/I/81WjalMN8mL._AC_SY200_.jpg",
    price: 1199.99,
    oldPrice: 1399.00,
    rating: 4.5,
    reviewsCount: "2,100",
    description: "Ultrawide gaming monitor with 240Hz refresh rate and 1ms response time for pro gamers.",
  },
  {
    id: "sl5-prod-508", // Unique ID for variant
    title: "Logitech MX Master 3S - Graphite Edition",
    image: "https://m.media-amazon.com/images/I/71nVIiWEcgL._AC_SY200_.jpg",
    price: 99.00,
    oldPrice: 110.00,
    rating: 4.8,
    reviewsCount: "12,000",
    description: "The Graphite variant of the world-class MX Master 3S. Premium texture and precision.",
  },
  {
    id: "sl5-prod-509",
    title: "ASUS Zenbook Duo Elite Bundle",
    image: "https://m.media-amazon.com/images/I/719R46dVUTL._AC_SY200_.jpg",
    price: 1599.00,
    oldPrice: 1750.00,
    rating: 4.8,
    reviewsCount: "1,400",
    description: "Elite bundle including the Zenbook Duo, a premium stylus, and a protective leather sleeve.",
  },
  {
    id: "sl5-prod-510",
    title: "Netgear Nighthawk Pro Gaming Edition",
    image: "https://m.media-amazon.com/images/I/61aPY8odPSL._AC_SY200_.jpg",
    price: 320.00,
    oldPrice: 380.00,
    rating: 4.7,
    reviewsCount: "4,300",
    description: "Specialized gaming router with low-ping software and advanced traffic prioritization.",
  },
  {
    id: "sl5-prod-511",
    title: "Apple Magic Keyboard - Space Gray",
    image: "https://m.media-amazon.com/images/I/414C25OyjML._AC_SY200_.jpg",
    price: 159.00,
    oldPrice: 189.00,
    rating: 4.9,
    reviewsCount: "15,300",
    description: "Limited edition Space Gray Magic Keyboard with numeric keypad and Touch ID support.",
  },
  {
    id: "sl5-prod-512",
    title: "WD Black 4TB High-Capacity SSD",
    image: "https://m.media-amazon.com/images/I/51+oMO+PTeL._AC_SY200_.jpg",
    price: 310.00,
    oldPrice: 350.00,
    rating: 4.8,
    reviewsCount: "3,400",
    description: "High-capacity 4TB NVMe SSD for heavy video editing and massive game libraries.",
  },
  {
    id: "sl5-prod-513",
    title: "Corsair Dominator Titanium 64GB RAM",
    image: "https://m.media-amazon.com/images/I/51IFiSD+kCL._AC_SY200_.jpg",
    price: 245.00,
    oldPrice: 280.00,
    rating: 4.9,
    reviewsCount: "1,200",
    description: "The peak of memory engineering. Massive 64GB capacity with ultra-low latency.",
  },
  {
    id: "sl5-prod-514",
    title: "Samsung Odyssey Neo G9 Mini-LED",
    image: "https://m.media-amazon.com/images/I/81WjalMN8mL._AC_SY200_.jpg",
    price: 1899.00,
    oldPrice: 2100.00,
    rating: 4.7,
    reviewsCount: "850",
    description: "Next-gen Mini-LED backlighting monitor for incredible contrast and breathtaking HDR gaming.",
  },
];

export default FifthCardData;