const categoriesData = [
  {
    id: "cat-electronics-01",
    title: "Elevate your Electronics",
    buttonText: "Discover more",
    items: [
      {
        id: "prod-electronics-hp-101", 
        name: "Headphones",
        img: "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2025/Q1DefectReduction/Fuji_Defect_Reduction_1x_Headphones._SY116_CB549022351_.jpg",
        price: 49.99, 
        oldPrice: 79.99,
        description: "High-fidelity wireless headphones with noise cancellation.",
        rating: 4.5,
        reviewsCount: "12,402",
      },
      {
        id: "prod-electronics-tab-102",
        name: "Tablets",
        img: "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2025/Q1DefectReduction/Fuji_Defect_Reduction_1x_Tablets._SY116_CB549022351_.jpg",
        price: 299.00,
        oldPrice: 349.99,
        description: "Powerful 10-inch tablet for work and entertainment.",
        rating: 4.8,
        reviewsCount: "8,920",
      },
      {
        id: "prod-electronics-gam-103",
        name: "Gaming",
        img: "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2025/Q1DefectReduction/Fuji_Defect_Reduction_1x_Gaming._SY116_CB549022351_.jpg",
        price: 59.99,
        oldPrice: 69.99,
        description: "Ergonomic gaming controller with haptic feedback.",
        rating: 4.7,
        reviewsCount: "15,100",
      },
      {
        id: "prod-electronics-spk-104",
        name: "Speakers",
        img: "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2025/Q1DefectReduction/Fuji_Defect_Reduction_1x_Speakers._SY116_CB549022351_.jpg",
        price: 85.50,
        oldPrice: 99.00,
        description: "Portable bluetooth speaker with deep bass and waterproof design.",
        rating: 4.3,
        reviewsCount: "5,600",
      },
    ],
  },
  {
    id: "cat-fitness-02",
    title: "Gear up to get fit",
    buttonText: "Discover more",
    items: [
      {
        id: "prod-fitness-cloth-201",
        name: "Clothing",
        img: "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2025/Q1DefectReduction/Fuji_Defect_Reduction_1x_Clothing._SY116_CB549022351_.jpg",
        price: 25.00,
        oldPrice: 35.00,
        description: "Breathable moisture-wicking athletic wear for gym and running.",
        rating: 4.4,
        reviewsCount: "2,300",
      },
      {
        id: "prod-fitness-track-202",
        name: "Trackers",
        img: "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2025/Q1DefectReduction/Fuji_Defect_Reduction_1x_Trackers._SY116_CB549022351_.jpg",
        price: 110.00,
        oldPrice: 149.00,
        description: "Advanced fitness tracker with heart rate and sleep monitoring.",
        rating: 4.6,
        reviewsCount: "9,150",
      },
      {
        id: "prod-fitness-equip-203",
        name: "Equipment",
        img: "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2025/Q1DefectReduction/Fuji_Defect_Reduction_1x_Equipment._SY116_CB549022351_.jpg",
        price: 150.00,
        oldPrice: 199.99,
        description: "Home workout essentials including dumbbells and resistance bands.",
        rating: 4.2,
        reviewsCount: "4,780",
      },
      {
        id: "prod-fitness-deal-204",
        name: "Deals",
        img: "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2025/Q1DefectReduction/Fuji_Defect_Reduction_1x_Deals_Fitness._SY116_CB549022351_.jpg",
        price: 15.99,
        oldPrice: 25.00,
        description: "Exclusive limited-time offers on fitness accessories.",
        rating: 4.5,
        reviewsCount: "1,200",
      },
    ],
  },
  {
    id: "cat-wireless-03",
    title: "Wireless Tech",
    buttonText: "Discover more",
    items: [
      {
        id: "prod-wireless-phone-301",
        name: "Smartphones",
        img: "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2024/BAU2024Aug/Smartphone_1x._SY116_CB566164844_.jpg",
        price: 699.00,
        oldPrice: 799.00,
        description: "Latest 5G smartphone with pro camera system.",
        rating: 4.9,
        reviewsCount: "22,000",
      },
      {
        id: "prod-wireless-watch-302",
        name: "Watches",
        img: "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2024/BAU2024Aug/Watches_1x._SY116_CB566164844_.jpg",
        price: 199.99,
        oldPrice: 249.99,
        description: "Stylish smartwatch with cellular connectivity.",
        rating: 4.7,
        reviewsCount: "11,200",
      },
      {
        id: "prod-wireless-hp-303",
        name: "Headphones",
        img: "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2024/BAU2024Aug/Headphone_1x._SY116_CB566164844_.jpg",
        price: 120.00,
        oldPrice: 150.00,
        description: "True wireless earbuds with long battery life.",
        rating: 4.6,
        reviewsCount: "33,500",
      },
      {
        id: "prod-wireless-tab-304",
        name: "Tablets",
        img: "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2024/BAU2024Aug/Tablet_1x._SY116_CB566164844_.jpg",
        price: 450.00,
        oldPrice: 499.00,
        description: "Slim and light tablet perfect for creative work.",
        rating: 4.8,
        reviewsCount: "5,400",
      },
    ],
  },
  {
    id: "cat-gaming-04",
    title: "Gaming merchandise",
    buttonText: "See more",
    items: [
      {
        id: "prod-gaming-app-401",
        name: "Apparel",
        img: "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/June/Fuji_Quad_Apparel_1x._SY116_CB667159060_.jpg",
        price: 19.99,
        oldPrice: 29.99,
        description: "Official gaming themed hoodies and t-shirts.",
        rating: 4.2,
        reviewsCount: "1,100",
      },
      {
        id: "prod-gaming-hat-402",
        name: "Hats",
        img: "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/June/Fuji_Quad_Hat_1x._SY116_CB667159060_.jpg",
        price: 14.50,
        oldPrice: 19.99,
        description: "Adjustable caps with iconic gaming logos.",
        rating: 4.1,
        reviewsCount: "850",
      },
      {
        id: "prod-gaming-fig-403",
        name: "Action Figures",
        img: "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/June/Fuji_Quad_Figure_1x._SY116_CB667159060_.jpg",
        price: 35.00,
        oldPrice: 45.00,
        description: "Highly detailed collectible action figures.",
        rating: 4.9,
        reviewsCount: "3,200",
      },
      {
        id: "prod-gaming-mug-404",
        name: "Mugs",
        img: "https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/June/Fuji_Quad_Mug_1x._SY116_CB667159063_.jpg",
        price: 12.99,
        oldPrice: 15.00,
        description: "Ceramic heat-changing mugs for gamers.",
        rating: 4.5,
        reviewsCount: "6,700",
      },
    ],
  },
];

export default categoriesData;